CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	role VARCHAR(20) NOT NULL DEFAULT 'cliente',
	direccion VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	nombre VARCHAR(100),
	rut VARCHAR(20)
);

CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	descripcion TEXT,
	precio VARCHAR(20) NOT NULL,
	marca VARCHAR(50),
	incluye VARCHAR(255),
	garantia VARCHAR(100),
	stock INTEGER,
	oferta BOOLEAN DEFAULT FALSE,
	servicio BOOLEAN DEFAULT FALSE,
	no_fisico BOOLEAN DEFAULT FALSE,
	destacado BOOLEAN DEFAULT FALSE,
	duracion VARCHAR(50),
	modalidad VARCHAR(50),
	ficha_pdf VARCHAR(255),
	disponible BOOLEAN DEFAULT true,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE images (
	id SERIAL PRIMARY KEY,
	url VARCHAR(255) NOT NULL
);

CREATE TABLE product_images (
	id SERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	image_id INTEGER NOT NULL REFERENCES images(id) ON DELETE CASCADE,
	orden INTEGER DEFAULT 1
);

CREATE TABLE orders (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	total INTEGER NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'pagado',
	numero_orden VARCHAR(32),
	productos JSON,
	pago VARCHAR(32),
	envio VARCHAR(32),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
	id SERIAL PRIMARY KEY,
	order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	product_id INTEGER NOT NULL REFERENCES products(id),
	quantity INTEGER NOT NULL,
	price INTEGER NOT NULL
);